# Generated by Django 3.2.18 on 2023-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_name', models.CharField(max_length=30)),
                ('delivery_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_sum', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('dispatch_date', models.DateTimeField()),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'statuses',
                'managed': False,
            },
        ),
    ]
