# Generated by Django 3.2.18 on 2023-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingMethod',
            fields=[
                ('processing_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('processing_method_name', models.CharField(max_length=30)),
                ('processing_method_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processing_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=10)),
                ('taste', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('sample', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoastingMethod',
            fields=[
                ('roasting_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('roasting_method_name', models.CharField(max_length=30)),
                ('roasting_method_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roasting_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=30)),
                ('variety_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'varieties',
                'managed': False,
            },
        ),
    ]
