# Generated by Django 3.2.18 on 2023-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'weight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeightSelection',
            fields=[
                ('weight_selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'weight_selection',
                'managed': False,
            },
        ),
    ]
