# Generated by Django 3.2.18 on 2023-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_weight_weightselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariety',
            fields=[
                ('product_variety_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_variety',
                'managed': False,
            },
        ),
    ]
